<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="iamnisar812" failures="1" tests="2" name="MyTest" time="6.813" errors="0" timestamp="2023-06-25T13:32:18 IST">
  <testcase classname="nahmed.Tests.SubmitOrderTest" name="submitOrder" time="2.847"/>
  <testcase classname="nahmed.Tests.SubmitOrderTest" name="submitOrder" time="6.803">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;com.aventstack.extentreports.ExtentTest.log(com.aventstack.extentreports.Status, String)&amp;quot; because the return value of &amp;quot;java.lang.ThreadLocal.get()&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "com.aventstack.extentreports.ExtentTest.log(com.aventstack.extentreports.Status, String)" because the return value of "java.lang.ThreadLocal.get()" is null
at nahmed.TestComponents.Listeners.onTestSuccess(Listeners.java:32)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- submitOrder -->
  <testcase classname="nahmed.Tests.SubmitOrderTest" name="OrderHistoryTest" time="0.0">
    <ignored/>
  </testcase> <!-- OrderHistoryTest -->
  <testcase classname="nahmed.Tests.ErrorValidationsTest" name="ProductErrorValidation" time="0.0">
    <ignored/>
  </testcase> <!-- ProductErrorValidation -->
</testsuite> <!-- MyTest -->
